"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "zh"

type TranslationKey = string

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: TranslationKey) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.capabilities": "Capabilities",
    "nav.projects": "Projects",
    "nav.governance": "Governance",
    "nav.resources": "Resources",
    "nav.compliance": "Compliance",

    // Home page
    "home.title": "Open Source Program Office",
    "home.subtitle": "Driving innovation through open source collaboration",
    "home.vision.title": "Our Vision",
    "home.vision.content":
      "To establish a thriving open source culture that drives innovation, collaboration, and technological excellence across our organization.",
    "home.mission.title": "Our Mission",
    "home.mission.content":
      "To enable and support open source adoption, contribution, and compliance throughout the organization while fostering a collaborative ecosystem with the broader open source community.",
    "home.responsibilities.title": "Key Responsibilities",
    "home.responsibilities.item1": "Open Source Strategy & Governance",
    "home.responsibilities.item2": "License Compliance & Risk Management",
    "home.responsibilities.item3": "Community Engagement & Contribution",
    "home.responsibilities.item4": "Developer Education & Enablement",
    "home.responsibilities.item5": "Project Incubation & Maintenance",
    "home.team.title": "Our Team",
    "home.team.director": "OSPO Director",
    "home.team.manager": "Program Manager",
    "home.team.engineer": "Open Source Engineer",
    "home.team.legal": "Legal Counsel",
    "home.team.developer": "Developer Advocate",
    "home.links.title": "Important Links",
    "home.links.internal": "Internal Resources",
    "home.links.external": "External Resources",

    // Capabilities page
    "capabilities.title": "Open Source Capabilities",
    "capabilities.subtitle": "Building excellence in open source practices",
    "capabilities.progress": "Progress",

    // Projects page
    "projects.title": "Open Source Projects",
    "projects.subtitle": "Our contributions to the open source ecosystem",
    "projects.internal": "Internal Projects",
    "projects.internal.desc": "Open source projects used internally within the organization, not publicly released.",
    "projects.external": "External Contributions",
    "projects.external.desc": "Our contributions to external open source projects and communities.",
    "projects.public": "Public Projects",
    "projects.public.desc": "Open source projects released publicly by our organization for the community.",
    "projects.status": "Status",
    "projects.active": "Active",
    "projects.maintenance": "Maintenance",
    "projects.incubating": "Incubating",
    "projects.repo": "Repository",
    "projects.maintainers": "Maintainers",
    "projects.contributors": "Contributors",
    "projects.contribution": "Contribution",
    "projects.merged": "Merged",
    "projects.forks": "Forks",

    // Governance page
    "governance.title": "Governance Policies",
    "governance.subtitle": "Open source governance framework, policies, and organizational structure",
    "governance.tab.policies": "Policies",
    "governance.tab.organization": "Organization",
    "governance.tab.operations": "Operations",
    "governance.policies.desc": "Comprehensive policies governing open source activities across the organization.",
    "governance.policy.overall.title": "Overall Open Source Policy",
    "governance.policy.overall.desc":
      "The foundational policy defining our approach to open source software usage, contribution, and release.",
    "governance.policy.contribution.title": "Contribution Policy",
    "governance.policy.contribution.desc":
      "Guidelines and requirements for contributing to external open source projects.",
    "governance.policy.usage.title": "Usage Policy",
    "governance.policy.usage.desc":
      "Standards for evaluating, approving, and using open source components in products.",
    "governance.policy.ip.title": "IP Rights Management",
    "governance.policy.ip.desc":
      "Intellectual property considerations and CLA requirements for open source activities.",
    "governance.updated": "Updated",
    "governance.view": "View Policy",
    "governance.org.desc": "The organizational structure supporting open source governance and operations.",
    "governance.org.committee": "Open Source Steering Committee",
    "governance.org.committee.desc": "Executive-level oversight and strategic direction for open source initiatives.",
    "governance.org.ospo": "Open Source Program Office",
    "governance.org.ospo.desc": "Central team responsible for implementing and managing open source programs.",
    "governance.org.ambassadors": "Open Source Ambassadors",
    "governance.org.ambassadors.desc": "Representatives across teams promoting open source best practices.",
    "governance.org.chart.title": "Organization Chart",
    "governance.org.chart.desc": "Hierarchical structure of open source governance",
    "governance.org.compliance": "Compliance Team",
    "governance.org.community": "Community Team",
    "governance.org.engineering": "Engineering Support",
    "governance.ops.desc": "Regular operations and workflows for open source governance.",
    "governance.ops.review.title": "Monthly Review Meeting",
    "governance.ops.review.desc": "Regular review of open source activities, metrics, and issues.",
    "governance.ops.review.freq": "Monthly",
    "governance.ops.approval.title": "Project Approval Process",
    "governance.ops.approval.desc": "Workflow for approving new open source usage or contributions.",
    "governance.ops.approval.freq": "On-demand",
    "governance.ops.audit.title": "Compliance Audit",
    "governance.ops.audit.desc": "Regular audit of open source compliance across all projects.",
    "governance.ops.audit.freq": "Quarterly",
    "governance.ops.report.title": "Executive Report",
    "governance.ops.report.desc": "Summary report on open source activities for leadership.",
    "governance.ops.report.freq": "Quarterly",
    "governance.details": "View Details",
    "governance.ops.workflow.title": "Standard Approval Workflow",
    "governance.ops.workflow.desc": "The process for getting open source usage or contribution approved",
    "governance.ops.step1": "Submit Request",
    "governance.ops.step2": "Initial Review",
    "governance.ops.step3": "Legal Review",
    "governance.ops.step4": "Security Scan",
    "governance.ops.step5": "Final Approval",

    // Resources page
    "resources.title": "Resource Center",
    "resources.subtitle": "Processes, guides, and success stories",
    "resources.processes.title": "Processes & Guides",
    "resources.cases.title": "Success Cases",
    "resources.processes.section": "Standard Processes",
    "resources.processes.desc": "Standard workflows for common open source activities.",
    "resources.guides.section": "Guides & Templates",
    "resources.guides.desc": "Helpful guides and templates to get you started.",
    "resources.process.contribution.title": "Contribution Workflow",
    "resources.process.contribution.desc": "Step-by-step process for contributing to open source projects.",
    "resources.process.license.title": "License Review Process",
    "resources.process.license.desc": "How to get approval for using new open source components.",
    "resources.process.release.title": "Project Release Process",
    "resources.process.release.desc": "Steps to release an internal project as open source.",
    "resources.process.security.title": "Security Review Process",
    "resources.process.security.desc": "Security assessment for open source components.",
    "resources.process.request.title": "Support Request Process",
    "resources.process.request.desc": "How to request OSPO support for your project.",
    "resources.process.incident.title": "Incident Response Process",
    "resources.process.incident.desc": "Handling compliance or security incidents.",
    "resources.guide.quickstart.title": "Quick Start Guide",
    "resources.guide.quickstart.desc": "Get started with open source contribution in your team.",
    "resources.guide.bestpractice.title": "Best Practices Guide",
    "resources.guide.bestpractice.desc": "Recommended practices for open source development.",
    "resources.guide.community.title": "Community Engagement Guide",
    "resources.guide.community.desc": "How to effectively participate in open source communities.",
    "resources.guide.cla.title": "CLA Template",
    "resources.guide.cla.desc": "Standard Contributor License Agreement template.",
    "resources.steps": "steps",
    "resources.view": "View",
    "resources.download": "Download",
    "resources.type.guide": "Guide",
    "resources.type.template": "Template",
    "resources.cases.desc": "Real success stories showcasing the impact of open source adoption.",
    "resources.case.department": "Department",
    "resources.case.impact.high": "High Impact",
    "resources.case.impact.medium": "Medium Impact",
    "resources.case.dept.cloud": "Cloud Infrastructure",
    "resources.case.dept.data": "Data Science",
    "resources.case.dept.eng": "Engineering",
    "resources.case.dept.support": "Customer Support",
    "resources.case.cloud.title": "Cloud Infrastructure Optimization",
    "resources.case.cloud.desc": "How our team leveraged open source tools to optimize cloud costs.",
    "resources.case.cloud.metric": "Cost Reduction",
    "resources.case.ml.title": "Machine Learning Pipeline",
    "resources.case.ml.desc": "Building an ML pipeline with open source frameworks.",
    "resources.case.ml.metric": "Dev Time Reduced",
    "resources.case.devtools.title": "Developer Productivity Tools",
    "resources.case.devtools.desc": "Internal tools built on open source that improved productivity.",
    "resources.case.devtools.metric": "Productivity Increase",
    "resources.case.support.title": "Customer Support Dashboard",
    "resources.case.support.desc": "Open source visualization tools that improved response time.",
    "resources.case.support.metric": "Response Time Improved",
    "resources.case.readmore": "Read Case Study",

    // Compliance page
    "compliance.title": "Compliance",
    "compliance.subtitle": "Open source license compliance management and governance",
    "compliance.tab.policy": "Policy",
    "compliance.tab.metrics": "Metrics",
    "compliance.tab.knowledge": "Knowledge Base",
    "compliance.tab.tools": "SCA Tools",
    "compliance.tab.supplyChain": "Supply Chain",
    "compliance.policy.overview": "Policy Overview",
    "compliance.policy.license.title": "License Compliance",
    "compliance.policy.license.desc":
      "Detailed organizational requirements for open source software license compliance, approval processes, and guidelines. Including license compatibility matrix and usage restrictions.",
    "compliance.policy.review.title": "Compliance Review Process",
    "compliance.policy.review.desc":
      "Standard process for introducing new open source components and updating existing ones, including necessary review steps and approval chain.",
    "compliance.policy.contacts.title": "Compliance Contacts",
    "compliance.policy.contacts.desc": "Compliance team contacts and on-call schedule for urgent compliance inquiries.",
    "compliance.contacts.title": "Compliance Contacts",
    "compliance.contacts.desc": "Contact our compliance team for urgent inquiries",
    "compliance.contacts.lead": "Compliance Lead",
    "compliance.contacts.leadRole": "Open Source Compliance Manager",
    "compliance.contacts.legal": "Legal Counsel",
    "compliance.contacts.legalRole": "IP & Open Source Legal Advisor",
    "compliance.metrics.scanned": "Components Scanned",
    "compliance.metrics.compliant": "Compliant Components",
    "compliance.metrics.issues": "Open Issues",
    "compliance.metrics.rate": "Compliance Rate",
    "compliance.metrics.distribution": "License Distribution",
    "compliance.metrics.distributionDesc": "Overview of open source licenses used across projects",
    "compliance.metrics.other": "Others",
    "compliance.kb.guides": "Compliance Guides",
    "compliance.kb.guide1": "Open Source License Guide",
    "compliance.kb.guide2": "License Compatibility Matrix",
    "compliance.kb.guide3": "SBOM Generation Guide",
    "compliance.kb.faqs": "Frequently Asked Questions",
    "compliance.kb.faq1": "How to request license review?",
    "compliance.kb.faq2": "What licenses are allowed?",
    "compliance.kb.faq3": "How to handle GPL dependencies?",
    "compliance.kb.training": "Training Materials",
    "compliance.kb.training1": "Open Source Compliance 101",
    "compliance.kb.training2": "License Identification Workshop",
    "compliance.kb.training3": "Advanced Compliance Certification",
    "compliance.tools.title": "SCA Tools",
    "compliance.tools.desc": "Software Composition Analysis tools for license and vulnerability scanning",
    "compliance.tools.blackduck": "Enterprise-grade open source management and compliance solution",
    "compliance.tools.snyk": "Developer-first security platform for vulnerability detection",
    "compliance.tools.fossa": "Automated open source license compliance and SBOM management",
    "compliance.tools.whitesource": "Open source security and license compliance management",
    "compliance.tools.active": "Active",
    "compliance.tools.evaluation": "Evaluation",
    "compliance.tools.integration": "Tool Integration Status",
    "compliance.tools.cicd": "CI/CD Pipeline Integration",
    "compliance.tools.repo": "Repository Scanning",
    "compliance.tools.sbom": "SBOM Auto-generation",
    "compliance.tools.configured": "Configured",
    "compliance.tools.inProgress": "In Progress",

    // Supply Chain
    "compliance.supplyChain.title": "Open Source Software Supply Chain",
    "compliance.supplyChain.desc": "Health assessment and risk analysis of open source software supply chain",
    "compliance.supplyChain.overallHealth": "Overall Health",
    "compliance.supplyChain.security": "Security",
    "compliance.supplyChain.securityDesc": "Vulnerability detection and security update status",
    "compliance.supplyChain.maintenance": "Maintenance",
    "compliance.supplyChain.maintenanceDesc": "Project activity and maintenance frequency",
    "compliance.supplyChain.community": "Community",
    "compliance.supplyChain.communityDesc": "Community activity and contributor diversity",
    "compliance.supplyChain.license": "License Compliance",
    "compliance.supplyChain.licenseDesc": "License compliance and risk assessment",
    "compliance.supplyChain.quality": "Code Quality",
    "compliance.supplyChain.qualityDesc": "Code quality metrics and test coverage",
    "compliance.supplyChain.riskTitle": "Risk Distribution",
    "compliance.supplyChain.highRisk": "High Risk Components",
    "compliance.supplyChain.highRiskDesc": "Critical vulnerabilities or license issues",
    "compliance.supplyChain.mediumRisk": "Medium Risk Components",
    "compliance.supplyChain.mediumRiskDesc": "Moderate risks requiring attention",
    "compliance.supplyChain.lowRisk": "Low Risk Components",
    "compliance.supplyChain.lowRiskDesc": "Healthy components with no significant issues",

    // Footer
    "footer.copyright": "© 2025 OSPO. All rights reserved.",
    "footer.contact": "Contact Us",
    "footer.sourceCode": "Source Code",
  },
  zh: {
    // Navigation
    "nav.home": "首页",
    "nav.capabilities": "能力建设",
    "nav.projects": "项目列表",
    "nav.governance": "治理政策",
    "nav.resources": "资源中心",
    "nav.compliance": "开源合规",

    // Home page
    "home.title": "开源项目办公室",
    "home.subtitle": "通过开源协作推动创新",
    "home.vision.title": "我们的愿景",
    "home.vision.content": "建立蓬勃发展的开源文化，推动整个组织的创新、协作和技术卓越。",
    "home.mission.title": "我们的使命",
    "home.mission.content": "在整个组织中支持开源采用、贡献和合规，同时与更广泛的开源社区建立协作生态系统。",
    "home.responsibilities.title": "主要职责",
    "home.responsibilities.item1": "开源战略与治理",
    "home.responsibilities.item2": "许可证合规与风险管理",
    "home.responsibilities.item3": "社区参与与贡献",
    "home.responsibilities.item4": "开发者教育与赋能",
    "home.responsibilities.item5": "项目孵化与维护",
    "home.team.title": "我们的团队",
    "home.team.director": "OSPO 主管",
    "home.team.manager": "项目经理",
    "home.team.engineer": "开源工程师",
    "home.team.legal": "法律顾问",
    "home.team.developer": "开发者倡导者",
    "home.links.title": "重要链接",
    "home.links.internal": "内部资源",
    "home.links.external": "外部资源",

    // Capabilities page
    "capabilities.title": "开源能力建设",
    "capabilities.subtitle": "构建开源实践卓越能力",
    "capabilities.progress": "进度",

    // Projects page
    "projects.title": "开源项目",
    "projects.subtitle": "我们对开源生态系统的贡献",
    "projects.internal": "内部开源项目",
    "projects.internal.desc": "组织内部使用的开源项目，未对外公开发布。",
    "projects.external": "参与外部贡献",
    "projects.external.desc": "我们对外部开源项目和社区的贡献。",
    "projects.public": "对外开源项目",
    "projects.public.desc": "我们组织对外公开发布的开源项目，供社区使用。",
    "projects.status": "状态",
    "projects.active": "活跃",
    "projects.maintenance": "维护中",
    "projects.incubating": "孵化中",
    "projects.repo": "仓库",
    "projects.maintainers": "维护者",
    "projects.contributors": "贡献者",
    "projects.contribution": "贡献内容",
    "projects.merged": "已合并",
    "projects.forks": "Fork数",

    // Governance page
    "governance.title": "治理政策",
    "governance.subtitle": "开源治理框架、政策与组织架构",
    "governance.tab.policies": "政策制度",
    "governance.tab.organization": "组织架构",
    "governance.tab.operations": "运作方式",
    "governance.policies.desc": "管理组织内开源活动的综合政策。",
    "governance.policy.overall.title": "开源总体政策",
    "governance.policy.overall.desc": "定义我们对开源软件使用、贡献和发布方法的基础性政策。",
    "governance.policy.contribution.title": "贡献政策",
    "governance.policy.contribution.desc": "向外部开源项目贡献代码的指南和要求。",
    "governance.policy.usage.title": "使用政策",
    "governance.policy.usage.desc": "评估、审批和在产品中使用开源组件的标准。",
    "governance.policy.ip.title": "知识产权管理",
    "governance.policy.ip.desc": "开源活动相关的知识产权考量和CLA要求。",
    "governance.updated": "更新日期",
    "governance.view": "查看政策",
    "governance.org.desc": "支持开源治理和运营的组织架构。",
    "governance.org.committee": "开源治理委员会",
    "governance.org.committee.desc": "为开源计划提供高管级别的监督和战略方向。",
    "governance.org.ospo": "开源项目办公室",
    "governance.org.ospo.desc": "负责实施和管理开源项目的核心团队。",
    "governance.org.ambassadors": "开源大使",
    "governance.org.ambassadors.desc": "在各团队推广开源最佳实践的代表。",
    "governance.org.chart.title": "组织架构图",
    "governance.org.chart.desc": "开源治理的层级结构",
    "governance.org.compliance": "合规团队",
    "governance.org.community": "社区团队",
    "governance.org.engineering": "工程支持",
    "governance.ops.desc": "开源治理的常规运作和工作流程。",
    "governance.ops.review.title": "月度审查会议",
    "governance.ops.review.desc": "定期审查开源活动、指标和问题。",
    "governance.ops.review.freq": "每月",
    "governance.ops.approval.title": "项目审批流程",
    "governance.ops.approval.desc": "审批新开源使用或贡献的工作流程。",
    "governance.ops.approval.freq": "按需",
    "governance.ops.audit.title": "合规审计",
    "governance.ops.audit.desc": "定期审计所有项目的开源合规情况。",
    "governance.ops.audit.freq": "每季度",
    "governance.ops.report.title": "高管报告",
    "governance.ops.report.desc": "向领导层汇报开源活动的总结报告。",
    "governance.ops.report.freq": "每季度",
    "governance.details": "查看详情",
    "governance.ops.workflow.title": "标准审批流程",
    "governance.ops.workflow.desc": "获得开源使用或贡献批准的流程",
    "governance.ops.step1": "提交申请",
    "governance.ops.step2": "初步审核",
    "governance.ops.step3": "法务审核",
    "governance.ops.step4": "安全扫描",
    "governance.ops.step5": "最终审批",

    // Resources page
    "resources.title": "资源中心",
    "resources.subtitle": "流程、指南和成功案例",
    "resources.processes.title": "流程与指南",
    "resources.cases.title": "成功案例",
    "resources.processes.section": "标准流程",
    "resources.processes.desc": "常见开源活动的标准工作流程。",
    "resources.guides.section": "指南与模板",
    "resources.guides.desc": "帮助您快速入门的有用指南和模板。",
    "resources.process.contribution.title": "贡献工作流",
    "resources.process.contribution.desc": "向开源项目贡献代码的逐步流程。",
    "resources.process.license.title": "许可证审查流程",
    "resources.process.license.desc": "如何获得使用新开源组件的批准。",
    "resources.process.release.title": "项目发布流程",
    "resources.process.release.desc": "将内部项目作为开源发布的步骤。",
    "resources.process.security.title": "安全审查流程",
    "resources.process.security.desc": "开源组件的安全评估流程。",
    "resources.process.request.title": "支持请求流程",
    "resources.process.request.desc": "如何为您的项目申请OSPO支持。",
    "resources.process.incident.title": "事件响应流程",
    "resources.process.incident.desc": "处理合规或安全事件的流程。",
    "resources.guide.quickstart.title": "快速入门指南",
    "resources.guide.quickstart.desc": "在您的团队中开始开源贡献。",
    "resources.guide.bestpractice.title": "最佳实践指南",
    "resources.guide.bestpractice.desc": "开源开发的推荐实践。",
    "resources.guide.community.title": "社区参与指南",
    "resources.guide.community.desc": "如何有效参与开源社区。",
    "resources.guide.cla.title": "CLA模板",
    "resources.guide.cla.desc": "标准贡献者许可协议模板。",
    "resources.steps": "步骤",
    "resources.view": "查看",
    "resources.download": "下载",
    "resources.type.guide": "指南",
    "resources.type.template": "模板",
    "resources.cases.desc": "展示开源采用影响力的真实成功案例。",
    "resources.case.department": "部门",
    "resources.case.impact.high": "高影响力",
    "resources.case.impact.medium": "中等影响力",
    "resources.case.dept.cloud": "云基础设施",
    "resources.case.dept.data": "数据科学",
    "resources.case.dept.eng": "工程团队",
    "resources.case.dept.support": "客户支持",
    "resources.case.cloud.title": "云基础设施优化",
    "resources.case.cloud.desc": "团队如何利用开源工具优化云成本。",
    "resources.case.cloud.metric": "成本降低",
    "resources.case.ml.title": "机器学习流水线",
    "resources.case.ml.desc": "使用开源框架构建ML流水线。",
    "resources.case.ml.metric": "开发时间减少",
    "resources.case.devtools.title": "开发者生产力工具",
    "resources.case.devtools.desc": "基于开源构建的内部工具提升了生产力。",
    "resources.case.devtools.metric": "生产力提升",
    "resources.case.support.title": "客户支持仪表板",
    "resources.case.support.desc": "开源可视化工具提高了响应时间。",
    "resources.case.support.metric": "响应时间改善",
    "resources.case.readmore": "阅读案例",

    // Compliance page
    "compliance.title": "开源合规",
    "compliance.subtitle": "开源许可证合规管理与治理",
    "compliance.tab.policy": "政策",
    "compliance.tab.metrics": "指标",
    "compliance.tab.knowledge": "知识库",
    "compliance.tab.tools": "SCA工具",
    "compliance.tab.supplyChain": "供应链",
    "compliance.policy.overview": "政策概览",
    "compliance.policy.license.title": "许可证合规",
    "compliance.policy.license.desc":
      "组织对开源软件许可证合规的详细要求、审批流程和指南，包括许可证兼容性矩阵和使用限制。",
    "compliance.policy.review.title": "合规审查流程",
    "compliance.policy.review.desc": "引入新开源组件和更新现有组件的标准流程，包括必要的审查步骤和审批链。",
    "compliance.policy.contacts.title": "合规联系人",
    "compliance.policy.contacts.desc": "合规团队联系方式及紧急合规咨询值班安排。",
    "compliance.contacts.title": "合规联系人",
    "compliance.contacts.desc": "如有紧急咨询请联系合规团队",
    "compliance.contacts.lead": "合规负责人",
    "compliance.contacts.leadRole": "开源合规经理",
    "compliance.contacts.legal": "法律顾问",
    "compliance.contacts.legalRole": "知识产权与开源法律顾问",
    "compliance.metrics.scanned": "已扫描组件",
    "compliance.metrics.compliant": "合规组件",
    "compliance.metrics.issues": "待处理问题",
    "compliance.metrics.rate": "合规率",
    "compliance.metrics.distribution": "许可证分布",
    "compliance.metrics.distributionDesc": "项目中使用的开源许可证概览",
    "compliance.metrics.other": "其他",
    "compliance.kb.guides": "合规指南",
    "compliance.kb.guide1": "开源许可证指南",
    "compliance.kb.guide2": "许可证兼容性矩阵",
    "compliance.kb.guide3": "SBOM生成指南",
    "compliance.kb.faqs": "常见问题",
    "compliance.kb.faq1": "如何申请许可证审查？",
    "compliance.kb.faq2": "哪些许可证是允许使用的？",
    "compliance.kb.faq3": "如何处理GPL依赖？",
    "compliance.kb.training": "培训材料",
    "compliance.kb.training1": "开源合规入门",
    "compliance.kb.training2": "许可证识别工作坊",
    "compliance.kb.training3": "高级合规认证",
    "compliance.tools.title": "SCA工具",
    "compliance.tools.desc": "用于许可证和漏洞扫描的软件成分分析工具",
    "compliance.tools.blackduck": "企业级开源管理和合规解决方案",
    "compliance.tools.snyk": "面向开发者的安全平台，用于漏洞检测",
    "compliance.tools.fossa": "自动化开源许可证合规和SBOM管理",
    "compliance.tools.whitesource": "开源安全和许可证合规管理",
    "compliance.tools.active": "使用中",
    "compliance.tools.evaluation": "评估中",
    "compliance.tools.integration": "工具集成状态",
    "compliance.tools.cicd": "CI/CD 流水线集成",
    "compliance.tools.repo": "代码仓库扫描",
    "compliance.tools.sbom": "SBOM 自动生成",
    "compliance.tools.configured": "已配置",
    "compliance.tools.inProgress": "进行中",

    // Supply Chain
    "compliance.supplyChain.title": "开源软件供应链",
    "compliance.supplyChain.desc": "开源软件供应链健康度评估和风险分析",
    "compliance.supplyChain.overallHealth": "整体健康度",
    "compliance.supplyChain.security": "安全性",
    "compliance.supplyChain.securityDesc": "漏洞检测和安全更新状态",
    "compliance.supplyChain.maintenance": "维护性",
    "compliance.supplyChain.maintenanceDesc": "项目活跃度和维护频率",
    "compliance.supplyChain.community": "社区活跃度",
    "compliance.supplyChain.communityDesc": "社区活跃度和贡献者多样性",
    "compliance.supplyChain.license": "许可证合规",
    "compliance.supplyChain.licenseDesc": "许可证合规性和风险评估",
    "compliance.supplyChain.quality": "代码质量",
    "compliance.supplyChain.qualityDesc": "代码质量指标和测试覆盖率",
    "compliance.supplyChain.riskTitle": "风险分布",
    "compliance.supplyChain.highRisk": "高风险组件",
    "compliance.supplyChain.highRiskDesc": "存在严重漏洞或许可证问题",
    "compliance.supplyChain.mediumRisk": "中风险组件",
    "compliance.supplyChain.mediumRiskDesc": "存在需要关注的中等风险",
    "compliance.supplyChain.lowRisk": "低风险组件",
    "compliance.supplyChain.lowRiskDesc": "健康组件,无重大问题",

    // Footer
    "footer.copyright": "© 2025 OSPO. 保留所有权利。",
    "footer.contact": "联系我们",
    "footer.sourceCode": "源代码",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("zh")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "zh")) {
      setLanguage(savedLanguage)
    } else {
      const browserLang = navigator.language.split("-")[0]
      if (browserLang === "zh") {
        setLanguage("zh")
      }
    }
  }, [])

  const handleSetLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage)
    localStorage.setItem("language", newLanguage)
  }

  const t = (key: TranslationKey): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
